// This is an example of a data analysis program.

// Every data analysis program reads data from the data/data_for_analysis folder
// (never raw data) and outputs a file to the results folder. 

// This program is called table01.do, which indicates it will produce the 
// results in Table 1 of the main text and output them to a file called
// table01.txt in the results folder.

// Always start by declaring the version and reading in the configuration file
version 19.5
if ("$programs" == "") {
	global programs "../"	
}
do "$programs/config.do"

// Read in the cleaned data
use "$data/data_for_analysis/auto_clean.dta", clear

// Check the data for changes
// This is a simple assert to catch unexpected changes to the data
assert _N == 74

// Modify the data as required
// This program should make as few modifications as possible to
// ensure that all analysis programs are working with consistent data.

// Produce the results
// This code calculates summary statistics and stores them in a matrix called
// Table01.
tabstat price mpg , stat(mean sd) save
matrix Table01 = r(StatTotal)

// Check the results for changes (optional)
// The code below was generated by Stata by executing the command
// "mkassert eclass" after executing the tabstat command above, and then editing
// the results. It creates a matrix (T_StatTotal) of past results, then
// compares that matrix to the current results. If they differ by more than
// 10^{-8}, Stata will stop the program and issue an error message.
quietly {
matrix T_StatTotal = J(2,2,0)
matrix T_StatTotal[1,1] =  6165.256756756757
matrix T_StatTotal[1,2] =   21.2972972972973
matrix T_StatTotal[2,1] =  2949.495884768919
matrix T_StatTotal[2,2] =  5.785503209735141
}
assert mreldif( Table01 , T_StatTotal ) < 1E-8
mat drop T_StatTotal

// Write the results to the results folder.
// I am doing this the old-fashioned way (creating a log file). Optional 
// packages will let you do better than that.
log using "$results/table01.txt" , text replace
matlist Table01 , title("Table 1: Summary statistics")
log close
